### ISSUE TITLE
Create onboarding document describing project

### ISSUE THREAD

**Issue by mbrajeux** [hackforla/heart#31]
- project history
- product description 
- team members + roles (including HEART team) 
- calendar / timeline

**Comment by gautham-l** [comment]
@mbrajeux This is Gautham, working on creating PRD guidelines and template (https://github.com/hackforla/product-management/issues/160). After reading the above comment, I assumed Onboarding document is quite similar to PRD. If so, can you please share the document with me or PRD if available?

Since, my first course action is to collect resources internally. I hope you don't mind me dropping a comment unrelated to this task.

Thanks in advance!
